@port=3000
@baseURL=http://localhost:{{port}}/users

### Criar usuário

POST {{baseURL}}/

{
    "name": "Melk de Sousa"
}

### Listar usuários

GET {{baseURL}}/

### Criar uma categoria
POST {{baseURL}}/categories
Content-Type: application/json
X-Owner: 65e23d60cc5c3a22873b8cc6

{
  "title": "Veículos Honda",
  "description": "Carros e Motos"
}

### Criar um produto

POST {{baseURL}}/products
Content-Type: application/json
X-Owner: 65e23d60cc5c3a22873b8cc6 

{
  "title": "POP 110",
  "description": "HONDA POP 110 Preta",
  "price": 1000000,
  "category": "65e23eafcc5c3a22873b8ccf"
}

### Atualizar um produto

PUT {{baseURL}}/products/65e23f00cc5c3a22873b8cd2
X-Owner: 65e23d60cc5c3a22873b8cc6

{
  "price": 1800000
}

### Consultar o catálogo do usuário

GET {{baseURL}}/catalogs
X-Owner: 65e23d60cc5c3a22873b8cc6
